version: '3.1'
services:
  sonarqube:
    image: sonarqube:7.7-community
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar?useUnicode=true&characterEncoding=utf8"
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - "sonarqube-net"
    depends_on:
      - postgres
  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_DB=sonar
    networks:
      - "sonarqube-net"
    volumes:
      - $HOME/data/volumes/postgres:/var/lib/postgresql/data
networks:
  sonarqube-net:
    driver: bridge